### ISSUE TITLE
Why disabling score fusion get even better results?

### ISSUE THREAD

**Issue by makecent** [happyharrycn/actionformer_release#48]
My understanding is that enabling score fusion will use the external classification score, which should lead to better results.
However, when I disabling the score fusion, i.e.,:
```yaml
# when using external scores, our model is generating "proposals"
# multiclass_nms: False,
# ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
# comment out L47-48 and uncomment L50 to disable score fusion
multiclass_nms: True,
```
The eval result is:
```shell
|tIoU = 0.30: mAP = 81.87 (%)
|tIoU = 0.40: mAP = 77.58 (%)
|tIoU = 0.50: mAP = 71.65 (%)
|tIoU = 0.60: mAP = 57.75 (%)
|tIoU = 0.70: mAP = 43.07 (%)
Avearge mAP: 66.38 (%)
```
While when enabling the score fusion, i.e.,:
```yaml
# when using external scores, our model is generating "proposals"
multiclass_nms: False,
ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
# comment out L47-48 and uncomment L50 to disable score fusion
# multiclass_nms: True,
```
I got a worse result:
```shell
|tIoU = 0.30: mAP = 74.82 (%)                  
|tIoU = 0.40: mAP = 71.34 (%)                
|tIoU = 0.50: mAP = 65.70 (%)            
|tIoU = 0.60: mAP = 55.28 (%)                   
|tIoU = 0.70: mAP = 41.97 (%)                
Avearge mAP: 61.82 (%)   
```
BTW, I did NOT retrain the model after revising the yaml because I think this should only do with the testing.
